# -*- coding: utf-8 -*-
"""桌宠生成模块：把 persona、立绘、配置组装成一套完整可运行的桌宠。"""

import json
import os
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core.studio_config import load_config as load_studio_config
from core.paths import app_dir, resource_dir

TEMPLATE_DIR = os.path.join(resource_dir(), "template")
DEFAULT_OUTPUT_ROOT = os.path.join(app_dir(), "output")

# 需要复制到每个桌宠的模板代码文件
TEMPLATE_FILES = [
    "main_pyside6.py",
    "ai_client.py",
    "search.py",
    "memory.py",
    "tts_client.py",
    "requirements.txt",
]


def _default_ai_config():
    return {
        "base_url": "http://localhost:11434/v1",
        "api_key": "ollama",
        "model": "qwen2.5vl:7b",
        "vision_model": "qwen2.5vl:7b",
        "temperature": 0.9,
        "max_history": 20,
        "keep_alive": "30m",
    }


def _build_config(ai_config, portraits, voice_config, pet_opts):
    cfg = {
        "ai": ai_config or _default_ai_config(),
        "portraits": portraits,
        "pet": {
            "always_on_top": pet_opts.get("always_on_top", True),
            "auto_watch_screen": pet_opts.get("auto_watch_screen", True),
            "screenshot_interval_sec": pet_opts.get("screenshot_interval_sec", 25),
        },
        "search": {
            "enabled": pet_opts.get("search_enabled", True),
            "max_results": pet_opts.get("search_max", 5),
        },
    }
    if voice_config:
        cfg["voice"] = {
            "enabled": True,
            "base_url": voice_config.get("base_url", "http://127.0.0.1:9880"),
            "ref_wav": voice_config.get("ref_wav", ""),
            "ref_text": voice_config.get("ref_text", ""),
            "ref_lang": voice_config.get("ref_lang", "中文"),
            "speed": voice_config.get("speed", 0.85),
        }
    return cfg


def _clean_bat(cmd_list):
    """把命令列表拼成 CRLF 的 bat 内容（纯 ASCII，避免 cmd 编码问题）。"""
    return "\r\n".join(cmd_list) + "\r\n"


def _build_launcher(pet_dir, has_voice, studio_cfg):
    """生成启动脚本内容。"""
    pythonw = studio_cfg.get("pythonw") or os.path.join(os.path.dirname(sys.executable), "pythonw.exe")
    gptsovits = studio_cfg.get("gptsovits_dir", "")

    clean = (
        'powershell -NoProfile -WindowStyle Hidden -Command "Get-CimInstance Win32_Process | '
        "Where-Object { ($_.Name -eq 'pythonw.exe' -or $_.Name -eq 'python.exe') -and "
        "($_.CommandLine -like '*main_pyside6.py*' -or $_.CommandLine -like '*main.py*' -or "
        "$_.CommandLine -like '*start_tts*.py*') } | "
        'ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }"'
    )

    lines = [
        "@echo off",
        "REM ============================================================",
        "REM  Desktop Pet launcher (generated by Pet Studio)",
        "REM ============================================================",
        "",
        "REM ---- Step 1: kill old pet processes first ----",
        clean,
        "",
        r"%SystemRoot%\System32\timeout.exe /t 3 /nobreak >nul",
        "",
    ]

    if has_voice and gptsovits:
        tts_py = os.path.join(gptsovits, "start_tts_user.py")
        tts_pythonw = os.path.join(gptsovits, "runtime", "pythonw.exe")
        lines += [
            "REM ---- Step 2: start TTS voice service ----",
            f'start "" "{tts_pythonw}" "{tts_py}" "{os.path.join(pet_dir, "config.json")}"',
            "",
        ]

    lines += [
        "REM ---- Step 3: start the pet ----",
        'cd /d "%~dp0"',
        f'start "" "{pythonw}" "%~dp0main_pyside6.py" config.json',
        "",
    ]
    return _clean_bat(lines)


def build_pet(
    role_name,
    persona_text,
    portraits,
    ai_config=None,
    voice_config=None,
    studio_cfg=None,
    output_root=None,
    pet_opts=None,
):
    """生成一套完整桌宠到 output/<role_name>/。

    参数：
        role_name    角色名（用作输出目录名）
        persona_text persona.txt 内容
        portraits    立绘列表，元素为 {"src": 源图片路径, "width": 显示宽度}
        ai_config    AI 配置 dict（缺省用本地 Ollama）
        voice_config 语音配置 dict（None 表示无语音）
        studio_cfg   全局配置（pythonw / gptsovits_dir）
        output_root  输出根目录
        pet_opts     桌宠行为选项（看屏间隔等）
    返回输出目录路径。
    """
    studio_cfg = studio_cfg or load_studio_config()
    pet_opts = pet_opts or {}
    output_root = output_root or DEFAULT_OUTPUT_ROOT
    pet_dir = os.path.join(output_root, role_name)

    os.makedirs(os.path.join(pet_dir, "assets"), exist_ok=True)

    # 1. persona.txt
    with open(os.path.join(pet_dir, "persona.txt"), "w", encoding="utf-8") as f:
        f.write(persona_text)

    # 2. 立绘
    portrait_entries = []
    for i, p in enumerate(portraits):
        src = p.get("src")
        if not src or not os.path.exists(src):
            continue
        ext = os.path.splitext(src)[1].lower()
        dst_name = f"portrait_{i + 1}{ext if ext == '.png' else '.png'}"
        dst = os.path.join(pet_dir, "assets", dst_name)
        # 已是 PNG 就直接复制；否则（jpg 等）交给立绘处理模块去背景
        from core.portrait_proc import process_portrait
        if ext == ".png":
            shutil.copyfile(src, dst)
        else:
            process_portrait(src, dst)
        portrait_entries.append({"file": dst_name, "width": p.get("width", 360)})

    if not portrait_entries:
        raise ValueError("没有有效的立绘图片")

    # 3. config.json
    config = _build_config(ai_config, portrait_entries, voice_config, pet_opts)
    with open(os.path.join(pet_dir, "config.json"), "w", encoding="utf-8") as f:
        json.dump(config, f, ensure_ascii=False, indent=2)

    # 4. 复制模板代码
    for name in TEMPLATE_FILES:
        shutil.copyfile(os.path.join(TEMPLATE_DIR, name), os.path.join(pet_dir, name))

    # 5. 启动脚本
    has_voice = bool(voice_config and voice_config.get("ref_wav"))
    bat = _build_launcher(pet_dir, has_voice, studio_cfg)
    with open(os.path.join(pet_dir, "启动桌宠.bat"), "w", encoding="ascii", newline="") as f:
        f.write(bat)

    return pet_dir


def create_desktop_shortcut(pet_dir, role_name, desktop=None):
    """在桌面创建该桌宠的启动快捷方式。返回 .lnk 路径。"""
    try:
        import win32com.client
    except ImportError:
        return None
    desktop = desktop or os.path.join(os.environ["USERPROFILE"], "Desktop")
    bat = os.path.join(pet_dir, "启动桌宠.bat")
    lnk = os.path.join(desktop, f"{role_name}-桌宠.lnk")
    shell = win32com.client.Dispatch("WScript.Shell")
    sc = shell.CreateShortcut(lnk)
    sc.TargetPath = bat
    sc.WorkingDirectory = pet_dir
    sc.Description = f"{role_name} 桌面桌宠"
    sc.Save()
    return lnk
